# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: swift

podfile: Example/Podfile

before_install:
  - which swiftlint || brew install swiftlint
  - gem install cocoapods

os: osx

osx_image:
  - xcode8

env:
  - TASK=lintpod
  - TASK=carthage

script:
  - rake ci:$TASK
